
#服务器配置
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: xxx@qq.com