
#服务器配置
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: drrnpxrdhuuphadd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: 1402548358@qq.com